### ISSUE TITLE
向一个无法连接的网络发送了一个套接字

### ISSUE THREAD

**Issue by TietiTage** [kaloronahuang/NCU-Srun-Python#2]
时隔两年的issue qwq，学长，我设置了脚本开机启动，为什么有时候弹出的命令提示符告诉我向一个无法连接的网络发送了一个套接字操作？有时候又可以登录成功，真是见了鬼了

**Comment by kaloronahuang** [comment]
请提供完整的错误信息，例如：

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spam' is not defined
```

谢谢。

**Comment by TietiTage** [comment]
Active code page: 65001
Traceback (most recent call last):
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001F796D0B8E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F796D0B8E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://222.204.3.154/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F796D0B8E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py", line 97, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py", line 93, in main
    getInfo()
  File "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py", line 23, in getInfo
    resp = requests.get(loginURL)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://222.204.3.154/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F796D0B8E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
登陆失败
Press any key to continue . . .
这是挂了梯子规则模式后会显示的报错，还有可能出现的报错为：

**Comment by TietiTage** [comment]
Active code page: 65001
Traceback (most recent call last):
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000178708EB850>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='222.204.3.154', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178708EB850>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py", line 97, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py", line 93, in main
    getInfo()
  File "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py", line 23, in getInfo
    resp = requests.get(loginURL)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='222.204.3.154', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178708EB850>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
登陆失败
Press any key to continue . . .

**Comment by kaloronahuang** [comment]
如果是梯子的问题，你可以尝试把 NCU 认证用的 IP（`222.204.3.154`）放到直连规则里。

**Comment by TietiTage** [comment]
> 如果是梯子的问题，你可以尝试把 NCU 认证用的 IP（`222.204.3.154`）放到直连规则里。

谢谢，这个问题似乎已经解决了，不过套接字的问题似乎仍然存在

**Comment by kaloronahuang** [comment]
这个问题本质上就是连不上 `222.204.3.154`，我也不太清楚 NCU 现在的网络环境有无变化。如果出现那样的问题，我建议你同时用浏览器开一下 `222.204.3.154` 看看能不能上。

**Comment by TietiTage** [comment]
> 这个问题本质上就是连不上 `222.204.3.154`，我也不太清楚 NCU 现在的网络环境有无变化。如果出现那样的问题，我建议你同时用浏览器开一下 `222.204.3.154` 看看能不能上。

是可以的，问了计算机的同学，说是学校垃圾服务器的问题？由于某种原因grab不到url。我不是计算机专业的同学，不太明白这个，但是他给出的建议是让代码多抓几遍

**Comment by TietiTage** [comment]
也有可能是学校屏蔽了脚本的登录功能？emm总之最近一个月，这个脚本似乎无法开机启动时生效了

> > 这个问题本质上就是连不上 `222.204.3.154`，我也不太清楚 NCU 现在的网络环境有无变化。如果出现那样的问题，我建议你同时用浏览器开一下 `222.204.3.154` 看看能不能上。
> 
> 是可以的，问了计算机的同学，说是学校垃圾服务器的问题？由于某种原因grab不到url。我不是计算机专业的同学，不太明白这个，但是他给出的建议是让代码多抓几遍

**Comment by kaloronahuang** [comment]
我不这么认为。“向一个无法连接的网络尝试了一个套接字操作”意味着你本机无法访问到这个 IP，你的机器找不到访问学校服务器 IP 的通路。你出现这个问题的时候，你需要查你的 IP 设置是否正确。可能你刚连上的时候还没有拿到 DHCP 下发的 IP 设置。

**Comment by TietiTage** [comment]
谢谢学长的提醒，按GPT的建议，我向自启动的bat脚本当中添加了一段多次尝试连接的代码：
```bat
@echo off
chcp 65001

set Counter=0

rem 定义网络检测函数
:CheckNetwork
    rem 使用ping命令检测网络连接
    ping -n 1 www.baidu.com > nul
    if %errorlevel% == 0 (
        echo 网络已连接
        goto StartLogin
    ) else (
        echo 等待网络连接...
        timeout /t 5 > nul
        set /a Counter+=1
        if %Counter% GEQ 6 (
            echo 尝试次数已达上限，仍无法连接网络。继续尝试登录...
            goto StartLogin
        )
        goto CheckNetwork
    )

    
:StartLogin
rem 执行Python脚本
"C:\Users\Tieti_Tage\AppData\Local\Programs\Python\Python310\python.exe" "C:\Program Files\JetBrains\PyCharm 2023.3.2\Py项目\NCU-Srun-Python-main\login.py"

if %ERRORLEVEL% == 0 (
    echo 登陆成功
) else (
    echo 登陆失败
)

pause

```
现在开机启动时不会显示这个报错了
